/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColecaoRouteImport } from './routes/colecao'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as SobreRouteImport } from './routes/sobre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoRoute = ColecaoRouteImport.update({
  id: '/colecao',
  path: '/colecao',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colecao': typeof ColecaoRoute
  '/faq': typeof FaqRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colecao': typeof ColecaoRoute
  '/faq': typeof FaqRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colecao': typeof ColecaoRoute
  '/faq': typeof FaqRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/colecao' | '/faq' | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colecao' | '/faq' | '/sobre'
  id: '__root__' | '/' | '/colecao' | '/faq' | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColecaoRoute: typeof ColecaoRoute
  FaqRoute: typeof FaqRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao': {
      id: '/colecao'
      path: '/colecao'
      fullPath: '/colecao'
      preLoaderRoute: typeof ColecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColecaoRoute: ColecaoRoute,
  FaqRoute: FaqRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
